# Generated by Django 4.2.20 on 2025-04-30 21:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('workload_hours', models.FloatField()),
                ('original_workload_hours', models.FloatField()),
                ('assigned_hours', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=30)),
                ('time_slot', models.CharField(max_length=20)),
                ('total_number_needed', models.IntegerField()),
                ('number_sup_wanted', models.IntegerField()),
                ('session_duration', models.FloatField()),
                ('responsibles', models.ManyToManyField(blank=True, related_name='responsibles_per_session', to='scheduler.teacher')),
                ('supervisors', models.ManyToManyField(blank=True, related_name='supervisers_per_session', to='scheduler.teacher')),
            ],
        ),
        migrations.CreateModel(
            name='Constraint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=20)),
                ('time_slot', models.CharField(max_length=20)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consraints', to='scheduler.teacher')),
            ],
            options={
                'unique_together': {('teacher', 'day', 'time_slot')},
            },
        ),
    ]
