# Generated by Django 4.2.20 on 2025-05-02 00:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='assigned_sessions',
            field=models.ManyToManyField(blank=True, related_name='assigned_teachers', to='scheduler.session'),
        ),
        migrations.AlterField(
            model_name='constraint',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consrtaints', to='scheduler.teacher'),
        ),
    ]
