# Generated by Django 4.2.20 on 2025-05-02 00:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0002_teacher_assigned_sessions_alter_constraint_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='constraint',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='constraints', to='scheduler.teacher'),
        ),
    ]
